### PR TITLE
Styled the final draw section and linked it to team pages

### PR DESCRIPTION
**Pull request by dhruv2185**
Aim of the project: Styling FINAL DRAW section of index.html and linking it to new webpage to display team info
Name: Dhruv Ghevariya
Github ID: dhruv2185
Role: Hacktoberfest 2022

I have styled the FINAL DRAW section using CSS and added animations to make it more interactive.
Also linked it to webpages corresponding to team info.
Screenshot (53)

Closes: #13

### CODE REVIEW

**Comment by dhruv2185** [comment]
I have done all the changes required by the template....

**Comment by Nirvik07** [comment]
@dhruv2185 doen't there any details in each team html file?

**Comment by dhruv2185** [comment]
No, details haven't been added...

**Comment by Nirvik07** [comment]
Ok @dhruv2185

**Review by Nirvik07 — APPROVED** [review]

**Comment by Nirvik07** [comment]
@dhruv2185 check everything and if you face  any problem with Hacktoberfest point system related to my repo, ping me in discord. Discord Id : babe07#7187

**Pull request merged**
