### PR TITLE
Add/aboutus

### PR DESCRIPTION
**Pull request by appledora**
## Issue Title : CREATE AN ABOUTUS PAGE 

- **Info about the related issue (Aim of the project)** : 
- **Name:** Appledora
- **GitHub ID:** Appledora
- **Idenitfy yourself:** Hacktoberfest Participant

Closes: #6

### Describe the add-ons or changes you've made 📃

* Created `about_us` folder inside the PROJECT directory with html files and related assets
* The AboutUs contains the details about FIFA WORLD CUP 2022.
* Design of the page matches with index page.
* 
screencapture-file-home-appledora-Documents-hacktoberfest-aboutus-PROJECTS-about-us-aboutus-html-2022-10-04-21_17_20

### CODE REVIEW

**Comment by appledora** [comment]
@Nirvik07 please check

**Comment by Nirvik07** [comment]
@appledora please follow this file https://github.com/Nirvik07/FIFA_WORLD_CUP_2022/blob/main/.github/PULL_REQEUST_TEMPLATE/pull_request_template.md for creating PR Template

**Comment by Nirvik07** [comment]
@appledora please pr the file in Project Folder.

**Comment by appledora** [comment]
@Nirvik07 I will modify the pr according the https://github.com/Nirvik07/FIFA_WORLD_CUP_2022/blob/main/.github/PULL_REQEUST_TEMPLATE/pull_request_template.md. 
But i am confused about what you meant by `PR the file in the project folder`. I created a folder inside the Project folder and kept my asssts and code inside it

**Comment by Nirvik07** [comment]
@appledora I want to tell you that did you uploaded your project in Projects Folder?

**Comment by appledora** [comment]
Yes,you can check the commit changes.

**Comment by Nirvik07** [comment]
@appledora if possible keep the Screenshot in description of PR details.

**Comment by appledora** [comment]
oh, i removed it because it wasn't in the PR template. adding

**Comment by Nirvik07** [comment]
@appledora don't edit the index.html. if possible, create a new index.html and put it inside your folder in the project folder, otherwise leave to me and delete the index.html in your PR.

**Comment by Nirvik07** [comment]
@appledora delete your index.html

**Comment by appledora** [comment]
@Nirvik07 check now

**Review by Nirvik07 — APPROVED** [review]
Everything is Ok. The Page is well designed . Keep coding and contribute more.
Your PR will be merged soon.

**Comment by Nirvik07** [comment]
@appledora check everything and if you face  any problem, ping me in discord. Discord Id : babe07#7187

**Pull request merged**
