### PR TITLE
Improved Navbar and footer

### PR DESCRIPTION
**Pull request by itshypon**
# Pull Request for FIFA WORLD CUP 2022 

## Issue Title : Improved Navbar, footer and minor changes

- **Info about the related issue (Aim of the project)** : Aim of the project is to give a better looking website
- **Name:** Himanshu
- **GitHub ID:** https://github.com/itshypon
- **Idenitfy yourself:** Hactoberfest Participant

Closes: #9 number that will be closed through this PR

### Describe the add-ons or changes you've made 📃

I have added navbar using bootstrap and did some changes in footer to make it look a little better. I changed font of some text to Montserrat and did a little change in one button.

### CODE REVIEW

**Comment by Nirvik07** [comment]
@itshypon please follow PR template in the repo for creating a pr.

**Comment by itshypon** [comment]
@Nirvik07 I am unable to find PR template in this repo. Should I use issue template or use PR template from any other repo?

**Comment by itshypon** [comment]
@Nirvik07 Done

**Comment by Nirvik07** [comment]
@itshypon  follow this file https://github.com/Nirvik07/FIFA_WORLD_CUP_2022/blob/main/.github/PULL_REQEUST_TEMPLATE/pull_request_template.md

**Comment by itshypon** [comment]
@Nirvik07 Done, Edited my PR

**Comment by itshypon** [comment]
@Nirvik07 When will this get merged?

**Review by Nirvik07 — APPROVED** [review]
Everyone is ok. The Page is web designed. Your PR will soon be merged.

**Comment by Nirvik07** [comment]
@itshypon did you create the pull request in projects folder?

**Comment by itshypon** [comment]
@Nirvik07 No, I just did pull request directly without any change so I guess it should be in main directory.

**Comment by Nirvik07** [comment]
@itshypon no please pr it to the projects folder. Otherwise my code will get deleted.

**Comment by itshypon** [comment]
@Nirvik07 These branches are available, to which branch should I send PR?
image

**Comment by Nirvik07** [comment]
@itshypon you will create your own branch. I will merge to the main branch.

**Comment by Nirvik07** [comment]
@itshypon if you are facing any problem, contact me in discord. Discord Id: babe07#7187

**Pull request closed without merging**
