### PR TITLE
Improved navbar and footer with minor font and button changes

### PR DESCRIPTION
**Pull request by itshypon**
# Pull Request for FIFA WORLD CUP 2022 

## Issue Title : Change navbar, footer and button design

- **Info about the related issue (Aim of the project)** : 
- **Name:** Himanshu
- **GitHub ID:** https://github.com/itshypon
- **Idenitfy yourself:** Hactoberfest Participant

Closes: #9
### Describe the add-ons or changes you've made 📃

I have added navbar using bootstrap and did some changes in footer to make it look a little better. I changed font of some text to Montserrat and did a little change in one button.

### CODE REVIEW

**Review by Nirvik07 — APPROVED** [review]
Everything is OK. The page is well designed. Your PR will be soon merged.

**Comment by Nirvik07** [comment]
@itshypon Write the issue title?

**Review by Nirvik07 — APPROVED** [review]

**Comment by itshypon** [comment]
@Nirvik07 Yeah done, kindly give it hacktoberfest-accepted label so that it will be added in my hactoberfest profile atleast.

**Comment by Nirvik07** [comment]
@itshypon all done check once.
delete the earlier pr.

**Comment by itshypon** [comment]
@Nirvik07 done

**Pull request merged**
